/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.artemas.codewars.fundamentals

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
